name: SpawnerGenz
description: ---
version: 1.0.0
author: xHyroM
main: me.xhyrom.spawnergenz.SpawnerGenz
api-version: 1.19

softdepend:
  - Essentials
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - PeddlersPocket